ifeq ($(OS), Windows_NT)
	TARGET = adivina.exe
	terminacion = exe
	cleanCommand = del
else
	TARGET = adivina.out
	terminacion = out
	cleanCommand = rm -f
endif

# Nombre del programa de salida
TARGET = adivina.$(terminacion)

# Objetivo predeterminado.
all: $(TARGET) # Se llama make all para correr todo.

# Compilador de C++
CXX = g++

SRCDIR = src

# Opciones de compilación
CXXFLAGS = -Wall -std=c++11 #Wall enseña todas las warnings de compilación.

# Lista de archivos fuente
SOURCES = main.cpp funciones.cpp

# Lista  de archivos objeto generados a partir de los archivos fuente
OBJECTS = $(SOURCES:.cpp=.$(terminacion)) # Es lo mismo que main.exe y estudiante.exe

# Regla para compilar los archivos fuente en archivos objeto.
%.$(terminacion): %.cpp 
	$(CXX) $(CXXFLAGS) -c $< -o $@

# El @ es en referencia al target (%.exe) y $< es la dependencia

# Regla para compilar el programa a partir de los archivos objeto.
$(TARGET): $(OBJECTS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJECTS)

# Regla para limpiar los archivos generados.
.PHONY: clean # Esto es para aclarale al makefile que no es un target de archivo y siempre correrlo aun si se encuentra actualizado.
clean:
	$(cleanCommand) $(TARGET) $(OBJECTS)
