CXX = g++
CXXFLAGS = -std=c++11 -Wall
SRCDIR = src
BINDIR = bin
SOURCES = $(wildcard $(SRCDIR)/*.cpp)
OBJECTS = $(SOURCES:$(SRCDIR)/%.cpp=$(BINDIR)/%.exe)
EXECUTABLE = adivina


all: build run

build: $(EXECUTABLE)

$(BINDIR)/%.exe: $(SRCDIR)/%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(EXECUTABLE): $(OBJECTS)
	$(CXX) $(OBJECTS) -o $(EXECUTABLE)


# Regla para ejecutar el programa
run:
	./$(EXECUTABLE)

clean:
	del $(EXECUTABLE)